const assert = require('node:assert/strict');
const {decode, pitchMatches, selectFiles, sortPitches, resolvePlayer, labelPlayer} = require('../web/conditional-finder/conditional-finder.js');
const defaults = () => ({role: 'pitcher', player: '', opponent: '', from: '', to: '', min: null, max: null, balls: null, strikes: null, action: '', types: [], calls: [], outcomes: [], allPA: false, team: '', stadium: '', inning: null, half: ''});
const game = {game_id: 'g', game_date: '2026-04-01', away_team: 'KIA', home_team: 'LG', stadium: '잠실'};
const pa = {id: 'pa', game, inning: 1, half: 'top', outcome: 'home_run'};
const first = {pa, pitcher: 'p', batter: 'b', number: 1, game_number: 1, type: 'FF', velocity: null, balls: 0, strikes: 0, action: 'take', call: 'B', terminal: false};
const last = {...first, pitcher: 'p2', number: 2, game_number: 2, velocity: 151.2, balls: 1, action: 'swing', call: 'X', terminal: true};
const matches = (pitch, options = {}) => pitchMatches(pitch, {...defaults(), ...options});
assert.ok(matches(first));
assert.ok(matches(first, {balls: 0, strikes: 0}));
assert.ok(!matches(first, {balls: 1}));
assert.ok(!matches({...first, balls: null}, {balls: 0}));
assert.ok(!matches(first, {min: 0})); // null ≠ zero
assert.ok(matches({...first, velocity: 0}, {min: 0, max: 0}));
assert.ok(matches(last, {min: 151.2, max: 151.2}));
assert.ok(!matches(last, {min: 151.3}));
assert.ok(matches(last, {types: ['FF', 'SL'], calls: ['X', 'S']}));
assert.ok(!matches(last, {types: ['SL'], calls: ['X']}));
assert.ok(!matches(first, {outcomes: ['home_run']}));
assert.ok(matches(last, {outcomes: ['home_run']}));
assert.ok(matches(first, {outcomes: ['home_run'], allPA: true}));
assert.ok(!matches(first, {outcomes: ['home_run'], allPA: true, action: 'swing'}));
for (const outcome of ['single', 'double', 'triple', 'home_run']) assert.ok(matches({...last, pa: {...pa, outcome}}, {outcomes: ['hit']}));
assert.ok(!matches({...last, pa: {...pa, outcome: 'error'}}, {outcomes: ['hit']}));
assert.ok(!matches(last, {outcomes: ['out']}));
assert.ok(matches(first, {role: 'pitcher', team: 'KIA'}));
assert.ok(matches(first, {role: 'batter', team: 'LG'}));
assert.ok(!matches(first, {role: 'batter', team: 'KIA'}));
assert.ok(matches({...first, pa: {...pa, half: 'bottom'}}, {role: 'pitcher', team: 'LG'}));
assert.ok(!matches({...first, pa: {...pa, half: null}}, {team: 'LG'}));
assert.ok(matches(last, {role: 'batter', player: 'b', opponent: 'p2', from: game.game_date, to: game.game_date}));
assert.ok(!matches(last, {player: 'p'}));
assert.ok(!matches(last, {from: '2026-04-02'}));
assert.ok(!matches(last, {to: '2026-03-31'}));
assert.ok(matches(first, {stadium: '잠실', inning: 1, half: 'top'}));
const index = {players: {pitcher: [{id: 'p', files: ['a', 'b']}], batter: [{id: 'b', files: ['b', 'c']}]}, files: [{file: 'a', date: '2026-04-01'}, {file: 'b', date: '2026-04-02'}, {file: 'c', date: '2026-04-03'}]};
assert.deepEqual(selectFiles(index, {...defaults(), player: 'p', opponent: 'b'}).map(x => x.file), ['b']);
assert.deepEqual(selectFiles(index, {...defaults(), role: 'batter', player: 'b', to: '2026-04-02'}).map(x => x.file), ['b']);
assert.deepEqual(selectFiles(index, {...defaults(), player: 'missing'}), []);
for (const order of ['fastest', 'slowest']) assert.equal(sortPitches([first, last], order).at(-1).velocity, null);
assert.equal(sortPitches([first, last], 'newest')[0], last);
assert.equal(sortPitches([first, last], 'oldest')[0], first);
const players = [{id: '1', name: '김선수', teams: ['KIA']}, {id: '2', name: '김선수', teams: ['LG']}];
assert.throws(() => resolvePlayer('김선수', players), /동명이인/);
assert.equal(resolvePlayer(labelPlayer(players[1]), players), '2');
assert.equal(resolvePlayer('1', players), '1');
assert.equal(resolvePlayer('  ', players), '');
assert.throws(() => resolvePlayer('존재하지 않음', players), /목록/);
const decoded = decode({schema_version: 1, games: {g: game}, pa_columns: ['id', 'game', 'outcome'], pas: [['pa', 'g', 'home_run']], columns: ['pa', 'pitcher', 'number'], rows: [[0, 'p', 1], [0, 'p2', 2]]});
assert.equal(decoded[0].pa, decoded[1].pa);
assert.equal(decoded[0].pa.pitches.length, 2);
assert.equal(decoded[0].pa.game, game);
assert.throws(() => decode({schema_version: 2}));
assert.throws(() => decode({schema_version: 1, games: {}, pa_columns: ['game'], pas: [['missing']], columns: [], rows: []}), /경기/);
console.log('PASS: Conditional Finder AND/OR, terminal/all-PA, null/zero, role/team, pruning, sort, homonyms, complete PA context');
